### ISSUE TITLE
[Contact] Order by number causes 500 error

### ISSUE THREAD

**Issue by Studio384** [optimise-group/bifrost#76]
**Describe the bug**
When ordering contacts by number, a 500 statuscode is returned.

**To Reproduce**
The given query:
```
  query Contacts(
    $organizationId: UUID4!,
    $paginateOffset: Int!,
    $orderDirection: OrderDirection!,
    $orderField: ContactOrderField!
  ) {
    contacts(
      organizationId: $organizationId,
      paginate: {
        limit: 50,
        offset: $paginateOffset
      },
      orderBy: {
        direction: $orderDirection,
        field: $orderField
      }
    ) {
      id,
      avatar,
      email,
      firstName,
      lastName,
      middleName,
      company,
      phoneNumbers {
        type,
        number
      },
      insertedAt,
      updatedAt
    }
  }
```

The given variables:
```
{
  "organizationId": "42ecb3de-be4c-477b-9cfe-aaccb7d9fd05",
  "paginateOffset": 0,
  "orderDirection": "ASC",
  "orderField": "NUMBER"
}
```

**Expected behavior**
A list of contacts is returned sorted by their number or `NUMBER` is not provided as a valid sort field.

**Current behavior**
Bifrost responds with the following:
```
{
  "data": {
    "contacts": null
  },
  "errors": [
    {
      "extensions": {
        "code": "UNKNOWN",
        "statusCode": 500
      },
      "locations": [
        {
          "column": 5,
          "line": 7
        }
      ],
      "message": "Something went wrong",
      "path": [
        "contacts"
      ]
    }
  ]
}
```

**Logs**
```
[debug] Processing with Absinthe.Plug.GraphiQL
  Parameters: %{"operationName" => "Contacts", "query" => "  query Contacts(\n    $organizationId: UUID4!,\n    $paginateOffset: Int!,\n    $orderDirection: OrderDirection!,\n    $orderField: ContactOrderField!\n  ) {\n    contacts(\n      organizationId: $organizationId,\n      paginate: {\n        limit: 50,\n        offset: $paginateOffset\n      },\n      orderBy: {\n        direction: $orderDirection,\n        field: $orderField\n      }\n    ) {\n      id,\n      avatar,\n      email,\n      firstName,\n      lastName,\n      middleName,\n      company,\n      phoneNumbers {\n        type,\n        number\n      },\n      insertedAt,\n      updatedAt\n    }\n  }", "variables" => %{"orderDirection" => "ASC", "orderField" => "NUMBER", "organizationId" => "42ecb3de-be4c-477b-9cfe-aaccb7d9fd05", "paginateOffset" => 0}}
  Pipelines: [:api, :graphql]
[debug] QUERY OK source="user_token" db=3.7ms queue=0.1ms idle=1952.1ms
SELECT u1."id", u1."avatar", u1."email_confirmed_at", u1."email", u1."first_name", u1."last_name", u1."middle_name", u1."password_hash", u1."inserted_at", u1."updated_at" FROM "user_token" AS u0 LEFT OUTER JOIN "user" AS u1 ON u0."assoc_id" = u1."id" WHERE ((u0."token" = $1) AND (u0."context" = $2)) AND (u0."inserted_at" > $3::timestamp + (-(60)::numeric * interval '1 day')) [<<52, 48, 40, 77, 1, 76, 225, 159, 5, 228, 169, 139, 124, 80, 21, 20, 217, 79, 223, 235, 230, 79, 138, 226, 92, 38, 64, 252, 43, 11, 178, 227>>, "session", ~U[2021-08-13 10:37:38.743530Z]]
[debug] ABSINTHE schema=Api.Schema variables=%{"orderDirection" => "ASC", "orderField" => "NUMBER", "organizationId" => "42ecb3de-be4c-477b-9cfe-aaccb7d9fd05", "paginateOffset" => 0}
---
query Contacts(
    $organizationId: UUID4!,
    $paginateOffset: Int!,
    $orderDirection: OrderDirection!,
    $orderField: ContactOrderField!
  ) {
    contacts(
      organizationId: $organizationId,
      paginate: {
        limit: 50,
        offset: $paginateOffset
      },
      orderBy: {
        direction: $orderDirection,
        field: $orderField
      }
    ) {
      id,
      avatar,
      email,
      firstName,
      lastName,
      middleName,
      company,
      phoneNumbers {
        type,
        number
      },
      insertedAt,
      updatedAt
    }
  }
---
[debug] QUERY ERROR source="contact" db=0.0ms queue=1.6ms idle=1977.5ms
SELECT c0."id", c0."avatar", c0."company", c0."email", c0."first_name", c0."last_name", c0."middle_name", c0."organization_id", c0."inserted_at", c0."updated_at" FROM "tenant"."contact" AS c0 WHERE (c0."organization_id" = $1) ORDER BY c0."number" LIMIT $2 OFFSET $3 [<<66, 236, 179, 222, 190, 76, 71, 123, 156, 254, 170, 204, 183, 217, 253, 5>>, 50, 0]
[error] ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.number does not exist

    query: SELECT c0."id", c0."avatar", c0."company", c0."email", c0."first_name", c0."last_name", c0."middle_name", c0."organization_id", c0."inserted_at", c0."updated_at" FROM "tenant"."contact" AS c0 WHERE (c0."organization_id" = $1) ORDER BY c0."number" LIMIT $2 OFFSET $3
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (api 0.1.0) lib/api/schema/resolvers/directory_resolver.ex:39: Api.Schema.Resolvers.Directory.list_contacts/3
    (absinthe 1.6.5) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
    (api 0.1.0) lib/api/schema/middleware/safe_resolution.ex:26: Api.Schema.Middleware.SafeResolution.call/2
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
    (absinthe 1.6.5) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
    (absinthe 1.6.5) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
    (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
    (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
    (phoenix 1.5.10) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
    (phoenix 1.5.10) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (api 0.1.0) lib/api/endpoint.ex:1: Api.Endpoint.plug_builder_call/2
    (api 0.1.0) lib/plug/debugger.ex:136: Api.Endpoint."call (overridable 3)"/2
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Erlang/Elixir version: Erlang 24, Elixier 1.12
 - Version/Commit: ceae8d0d

**Additional context**
NA

**Comment by timothyvanderaerden** [comment]
This is now fixed in bcc1af6. The `ContactOrderField` enum shouldn't contain `NUMBER` as an option (this has now been removed), to order by numbers `ContactPhoneNumberOrderBy` should be used.

Example:
```gql
query Contacts(
  $organizationId: UUID4!,
  $paginateOffset: Int!,
  $orderDirection: OrderDirection!,
  $orderField: ContactOrderField!,
  $orderPhoneNumberDirection: OrderDirection!,
  $orderPhoneNumberField: ContactPhoneNumberOrderField!
) {
  contacts(
    organizationId: $organizationId,
    paginate: {limit: 50, offset: $paginateOffset},
    orderBy: {direction: $orderDirection, field: $orderField}
  ) {
    id
    avatar
    email
    firstName
    lastName
    middleName
    company
    phoneNumbers(orderBy: {direction: $orderPhoneNumberDirection, field: $orderPhoneNumberField}) {
      type
      number
    }
    insertedAt
    updatedAt
  }
}
```

```json
{
  "organizationId": "42ecb3de-be4c-477b-9cfe-aaccb7d9fd05",
  "paginateOffset": 0,
  "orderDirection": "ASC",
  "orderField": "FIRST_NAME",
  "orderPhoneNumberDirection": "ASC" ,
  "orderPhoneNumberField": "NUMBER"
}
```

**Comment by Studio384** [comment]
A similar issue occures when using the `number` field in the `filter` despite `ContactFilter` marking it as a valid field.

```
{
  "errors": [
    {
      "locations": [
        {
          "column": 7,
          "line": 12
        }
      ],
      "message": "Argument \"filter\" has invalid value $filter.\nIn field \"number\": Unknown field."
    }
  ]
}
```

**Comment by Studio384** [comment]
It does according to the GraphQL Schema:

![image](https://user-images.githubusercontent.com/1693592/129726635-019059ae-c69b-4721-a917-1f12fe811aea.png)

**Comment by timothyvanderaerden** [comment]
Are you using the latest version and have you reloaded the GraphQL Playground? You can also set this so it reloads every 2 seconds

![image](https://user-images.githubusercontent.com/7502104/129728874-3fe048bd-4275-4deb-99a9-516f30fe36c4.png)
